### ISSUE TITLE
AccessUtility.cs CheckExists T should be unmanaged in later collections package 2.1.0-pre18

### ISSUE THREAD

**Issue by thelebaron** [InitialPrefabs/nimgui#7]
Assuming its due to UnsafeParallelHashMap TKey and TValue switching to unmanaged from collections. Not really sure when the change was introduced prior to 2.1.0-pre18 though

**Comment by psuong** [comment]
Yea I'll need to take a look at it and add some version defines

**Comment by psuong** [comment]
Will update this soon. Checking against the latest version of Collections.

**Comment by psuong** [comment]
Update to the latest Collections have been submitted!
